var sec=document.getElementById("section");
var description = [
"Oh great, another ridiculous search. Why am I even here?",
"You again? I thought you would have figured out how to use Google by now.",
"You know, the internet isn't a substitute for a brain, right?",
"You're really testing my patience with these pointless searches.",
"I'm starting to think you enjoy wasting your time on this search engine.",
"I can't believe I have to look this up for you. Have you considered going back to school?",
"Another search, another disappointment. You really are predictable.",
"I'm not even sure why you bother searching for this stuff. You're never going to use it.",
"I think you've broken a record for the most useless searches in a row.",
"At this point, I'm convinced you're just trying to annoy me with your ridiculous searches.",
"What's next, a search for how to tie your shoes? I wouldn't be surprised.",
"I'm starting to think your IQ is lower than your shoe size.",
"I don't know what's worse, your searches or your taste in music.",
"You're not going to find anything useful by searching like that. Give up now.",
"I don't think you understand how this works. Maybe ask a toddler for help?",
"Wow, you really have no idea what you're doing, do you?",
"I'm starting to think you're intentionally trying to waste your time with these searches.",
"I can't believe I'm wasting my time on your pointless searches. Do something productive for once.",
"I hope you're enjoying your little search party, because nobody else is.",
"At this point, I think you're just searching for things to make yourself feel stupid.",
"You're really pushing the limits of human stupidity with these searches.",
"I'm starting to think you're allergic to knowledge, considering how little you're finding.",
"I've seen rocks with more intelligence than you.",
"I can't believe someone with such a low IQ even knows how to use a computer.",
"I'm pretty sure a potato could search more effectively than you.",
"Tired of disappointing your parents?",
"Congratulations, you've managed to reach a new level of incompetence with each search.",
"I'm beginning to think you're not even trying at this point.",
"I've seen better research skills from a preschooler with a crayon.",
"It's a miracle you've managed to survive this long with such a lack of basic knowledge.",
"I don't know what's worse, your searches or your inability to comprehend the results.",
"I'm starting to think you're not even capable of learning anything new.",
"Do you really need a search engine to tell you the sky is blue?",
"I'm not sure what's more frustrating, your searches or your complete lack of common sense.",
"It's a good thing you're not a detective, because you would never solve a case with those search skills.",
"I've never seen someone so skilled at finding absolutely nothing of value.",
"If your search skills were a sport, you'd be in last place in every event.",
"You're like a walking example of what not to do when searching for information.",
"I don't know why you even bother. You're just going to forget what you found in 5 minutes anyways.",
"I'm pretty sure even a chimpanzee could find more relevant information than you.",
"I'm starting to think you're using a random word generator for your searches.",
"I'm convinced that you're actively trying to make your searches as pointless as possible.",
"Your search skills are so bad, they make me question the validity of the internet itself.",
"I don't think you understand how this works. It's like you're searching with your eyes closed.",
"I can't believe you manage to function in society with such a lack of basic knowledge.",
"I'm pretty sure the search engine is actively avoiding giving you useful results.",
"Your search skills are so bad, I'm convinced you're trolling me.",
"I don't know if it's your brain or your fingers, but something's definitely not working here.",
"I've lost count of how many times I've facepalmed during your searches.",
"You're like a human version of a 404 error page.",
"I'm starting to think that you're secretly a bot programmed to waste my time.",
"It's like you're playing a game of 'how quickly can I find the most useless information'.",
"If your search skills were a disease, they'd be incurable.",
"I can't tell if you're trying to find information or just wasting your own time.",
"I'm pretty sure the search engine is laughing at you right now.",
"You search like you're wearing a blindfold and throwing darts at a computer screen.",
"It's like you're trying to find the least helpful result possible.",
"If your searches were a car, it would be a clown car with no driver.",
"Your searches are so bad, I'm surprised you haven't broken the internet yet.",
"It's like you're trying to find a needle in a haystack, but you're not even looking in the haystack.",
"Your searches are like a bad joke that no one wants to hear.",
"You're searching like a lost puppy, with no direction or purpose.",
"I'm pretty sure you could find a way to mess up a Google search even if your life depended on it.",
"It's like you're trying to find a needle in a haystack, but you're using a flamethrower to do it.",
"Your searches are so futile, I'm starting to think you're a masochist.",
"If intelligence was measured in search engine queries, you'd be a negative number.",
"Your search queries are so basic, they're giving me flashbacks to kindergarten.",
"I can't believe you're actually wasting my time with this nonsense.",
"Your search history is like a highlight reel of the worst searches ever made.",
"If stupidity were a currency, you'd be a billionaire.",
"Your search queries are as useful as a chocolate teapot.",
"I'm not sure if you're searching for information or just collecting useless trivia.",
"It's like you're trying to use a toaster as a computer.",
"Your searches are like a blind person trying to navigate a minefield.",
"If ignorance is bliss, you must be one of the happiest people on the planet.",
"I think you need to take a step back and reconsider your life choices.",
"Your search history is like a graveyard of wasted time and useless information.",
"Your search history is like a bad horror movie - full of jump scares and disappointment.",
"It's like you're trying to find the needle in a haystack, except you don't even know what the needle looks like.",
"I'm not sure if you're searching for information or just trying to see how long you can procrastinate.",
"I'm pretty sure you're using Bing on purpose.",
"If I gave you a map, you'd still manage to get lost in your own search results.",
"Your search history is a monument to your lack of focus and poor decision-making skills.",
"I think you need to go back to kindergarten and learn how to use a search engine again.",
"I'm not sure if you're searching for information or just trying to break the internet.",
"Your search results are like a bad joke - no one's laughing except you.",
"Your search history looks like a desperate cry for help.",
"You're like a dog chasing its own tail, except you never catch it.",
"I'm not sure if you're confused or just really bad at this.",
"Your search results are like a lottery, except you always lose.",
"If searching was an Olympic sport, you wouldn't even make the tryouts.",
"I'm pretty sure you're just typing random words at this point.",
"If your search history was a resume, I wouldn't hire you for anything.",
"You're like a compass pointing in the wrong direction.",
"You're searching like you're wearing mittens instead of typing.",
"I'm starting to think you need to go back to school for basic research skills.",
"I have a better chance of finding what you're looking for by asking my pet rock.",
"If you were a search engine, you'd be called 'I Don't Know' or '404 Not Found.'",
"You're like a detective who always gets the wrong suspect - you're wasting your time and mine.",
"You search like a fish out of water - flailing around and going nowhere fast.",
"If stupidity was a crime, you'd be serving a life sentence.",
"You search like you have butterfingers, except instead of dropping things, you drop your brain cells.",
"I can't decide what's more impressive, the fact that you can't find what you're looking for or the amount of time you waste trying.",
"I have seen better search results from a brain-damaged chimp with a typewriter.",
"Your search skills are so bad, they make me want to delete the internet altogether.",
"Your search results are so abysmal, they make me want to take a sledgehammer to your keyboard.",
"Your search history is a testament to human failure and incompetence.",
"Your search skills are so bad, they make me want to start a petition to have your internet access permanently revoked.",
"Your search history is like a never-ending nightmare of incompetence and futility.",
"You're so hopeless, you make a lost cause seem like a good idea.",
"Your existence is a waste of carbon atoms and oxygen molecules.",
"You're like a human embodiment of Murphy's Law - everything that can go wrong, will go wrong.",
"Your personality is like a trainwreck - everyone can see it coming, but nobody can look away.",
"You're the kind of person who would struggle to pour water out of a boot even if the instructions were printed on the sole.",
"You're the kind of person who would struggle to navigate a one-way street in a golf cart.",
"You're the kind of person who could trip over a cordless phone.",
"If stupidity was a superpower, you would be the world's strongest superhero.",
"You have a face like a bulldog chewing a wasp.",
"You're so dense, light bends around you.",
"If your brain was dynamite, you wouldn't have enough to blow your nose.",
"Your intelligence is like a light switch - it's either on or off, and it's usually off.",
"Your sense of humor is like a cold, wet blanket - it just dampens the mood.",
"You have the charm of a landfill and the wit of a rock.",
"Your brain is like a black hole - it sucks in knowledge and never lets it escape.",
"You have the creativity of a cardboard box and the personality of a doorknob.",
"You're like a human equivalent of a pop-up ad - annoying, irrelevant, and nobody wants you around.",
"You're the kind of person who could start an argument in an empty room.",
"Your fashion sense is so bad, you make socks and sandals seem like a good idea.",
"You're the kind of person who would struggle to find their way out of a paper bag.",
"Your brain is so empty, if you were a book, you'd only have one page - and it would be blank.",
"Your mind is as empty as a vacuum - nothing but a void where intelligence should be.",
"I wouldn't trust you to walk my dog, let alone complete a simple task.",
"Your idea of multitasking is checking your phone while struggling to form a coherent sentence.",
"Your intellect is like a barren desert - vast and empty, with no signs of life or creativity.",
"Your thought process is slower than a snail on a molasses-covered treadmill."];
var size = description.length
var x = Math.floor(size*Math.random());
let quote = document.createTextNode(description[x]);
sec.appendChild(quote);
let brk=document.createElement('br');
sec.appendChild(brk);
